trigger:
  branches:
    include:
      - dev
      - feature/*

pool:
  vmImage: 'windows-latest' 

stages:
  - stage: test
    displayName: 'Testing Backend & Frontend'
    jobs:
      - job: Backend
        displayName: 'Backend Testing'
        steps:
            # Temporarily save secure file for testing .env
          - task: DownloadSecureFile@2
            inputs:
              secureFile: '.env'
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Use Node.js (Backend)'

          - script: npm ci
            workingDirectory: backend
            displayName: 'Install Backend Dependencies'

          - script: npm test
            workingDirectory: backend
            displayName: 'Run Backend Unit Tests;

      - job: Vitest
        displayName: 'Run Vitest Tests'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Use Node.js'

          - script: npm ci
            workingDirectory: frontend
            displayName: 'Install Frontend Dependencies'

          - script: npm run test
            workingDirectory: frontend
            displayName: 'Run Vitest Unit Tests'

          - script: npm run build
            workingDirectory: frontend
            displayName: 'Build Frontend'