trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: test
    displayName: 'Testing Backend & Frontend'
    jobs:
      # Backend Job
      - job: Backend
        displayName: 'Backend Testing'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Use Node.js (Backend)'

          - script: |
              echo "Backend directory contents:"
              ls -la
              echo "Package.json exists:"
              cat package.json | head -10
            workingDirectory: backend
            displayName: 'Debug Backend Environment'

          - script: npm ci
            workingDirectory: backend
            displayName: 'Install Backend Dependencies'

          - script: npm test
            workingDirectory: backend
            displayName: 'Run Backend Unit Tests'

      - job: Vitest
        displayName: 'Run Vitest Tests'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Use Node.js'

          # Debug frontend environment
          - script: |
              echo "Frontend directory contents:"
              ls -la
              echo "Package.json exists:"
              cat package.json | head -10
              echo "Node version: $(node --version)"
              echo "NPM version: $(npm --version)"
            workingDirectory: frontend
            displayName: 'Debug Frontend Environment'

          # Install dependencies with more verbose output
          - script: |
              npm ci --verbose
            workingDirectory: frontend
            displayName: 'Install Frontend Dependencies'

          # Force install the missing Rollup binary
          - script: |
              npm install @rollup/rollup-linux-x64-gnu --save-dev
            workingDirectory: frontend
            displayName: 'Install Missing Native Binary'
            continueOnError: true

          # Run tests
          - script: npm run test
            workingDirectory: frontend
            displayName: 'Run Vitest Unit Tests'

          # Build (move to end and make optional)
          - script: npm run build
            workingDirectory: frontend
            displayName: 'Build Frontend'
            continueOnError: true