trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: test
    displayName: 'Testing Backend & Frontend'
    jobs:
      - job: Backend
        displayName: 'Backend Testing'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Use Node.js (Backend)'

          - script: npm ci
            workingDirectory: backend
            displayName: 'Install Backend Dependencies'

          - script: npm test
            workingDirectory: backend
            displayName: 'Run Backend Unit Tests'

      - job: Vitest
        displayName: 'Run Vitest Tests'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Use Node.js'

          # Install dependencies
          - script: npm ci
            workingDirectory: frontend
            displayName: 'Install Frontend Dependencies'

          # Install missing native binaries
          - script: |
              npm install @parcel/watcher-linux-x64-glibc --save-dev --force
              npm install lightningcss-linux-x64-gnu --save-dev --force
            workingDirectory: frontend
            displayName: 'Install Missing Native Binaries'
            continueOnError: true

          # Run tests
          - script: npm run test
            workingDirectory: frontend
            displayName: 'Run Vitest Unit Tests'

          # Build
          - script: npm run build
            workingDirectory: frontend
            displayName: 'Build Frontend'