trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: test
    displayName: 'Testing Backend & Frontend'
    jobs:
      - job: Backend
        displayName: 'Backend Testing'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x' # Use Node LTS for stability
            displayName: 'Use Node.js (Backend)'

          - script: |
              cd backend
              npm ci
            displayName: 'Install Backend Dependencies'

          - script: |
              cd backend
              npm test
            displayName: 'Run Backend Unit Tests'

      - job: Frontend
        displayName: 'Frontend Testing'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x' # Use Node LTS for stability
            displayName: 'Use Node.js (Frontend)'

          - script: |
              cd frontend
              npm ci
            displayName: 'Install Frontend Dependencies'

          - script: |
              cd frontend
              export ROLLUP_SKIP_NATIVE=true
              npm run test -- --run
            displayName: 'Run Frontend Unit Tests (Vitest)'

          - script: |
              cd frontend
              export ROLLUP_SKIP_NATIVE=true
              npm run build
            displayName: 'Run Frontend Build'
