trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: FrontendBuild
  displayName: 'Build Frontend'
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '22.x'
    - script: |
        cd frontend
        npm install
        npm run build
      displayName: 'Build React Frontend'

- job: BackendBuild
  displayName: 'Build Backend'
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '22.x'
    - script: |
        cd backend
        npm install
      displayName: 'Build Node Backend'

