trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: test
    displayName: 'Testing Backend & Frontend'
    jobs:

      # Backend Job
      - job: Backend
        displayName: 'Backend Testing'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Use Node.js (Backend)'

          - script: npm ci
            workingDirectory: backend
            displayName: 'Install Backend Dependencies'

          - script: npm test
            workingDirectory: backend
            displayName: 'Run Backend Unit Tests'

      # Frontend Job
      - job: Frontend
        displayName: 'Frontend Testing'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Use Node.js (Frontend)'

          # Install dependencies
          - script: npm ci
            workingDirectory: frontend
            displayName: 'Install Frontend Dependencies'

          # Run Vitest tests with Rollup JS fallback
          - script: npx vitest run
            workingDirectory: frontend
            displayName: 'Run Frontend Unit Tests (Vitest)'
            env:
              ROLLUP_SKIP_NATIVE: 'true'

          # Build frontend with Rollup JS fallback
          - script: npx vite build
            workingDirectory: frontend
            displayName: 'Run Frontend Build'
            env:
              ROLLUP_SKIP_NATIVE: 'true'
