trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: test
    displayName: 'Testing Backend & Frontend'
    jobs:
      - job: Backend
        displayName: 'Backend Testing'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '22.x'

          - script: |
              cd backend
              npm install
            displayName: 'Install Backend Dependencies'

          - script: |
              cd backend
              npm test
            displayName: 'Run Backend Unit Tests'

      - job: Frontend
        displayName: 'Frontend Testing'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '22.x'

          - script: |
              cd frontend
              npm install
            displayName: 'Install Frontend Dependencies'

          - script: |
              cd frontend
              npm test
            displayName: 'Run Frontend Unit Tests'

          - script: |
              cd frontend
              npm run build
            displayName: 'Run Frontend Build'